### ISSUE TITLE
Delete not working

### ISSUE THREAD

**Issue by ThomasFont3721** [dixplo/Projet-Board#1]
https://github.com/dixplo/Projet-Board/blob/c2f6b8af45a91742e77ceb99d2dfa0dd7afc2df3/app/routes/developers/delete.js#L14

@jcheron 
Bonjour monsieur,
j'ai un petit problème avec mon delete je ne comprend pas pourquoi il ne fonctionne pas ?

**Comment by jcheron** [comment]
Et pourquoi vous n'utilisez pas le `dev` passé en param?
```
deleteForever(dev) {
            dev.destroyRecord().then(()=>this.transitionTo('developers'));
        }

**Comment by ThomasFont3721** [comment]
il ne fonctionne pas non plus quand je click cela le supprime bien mais si je reload la page les données revienne

**Comment by jcheron** [comment]
Vous êtes certain que c'est un dev qui a été créé avec l'application ?
Ceux qui ont été créés directement à partir de mongo ne peuvent être supprimés qu'à partir de Mongo compte tenu du système d'identifiants différent.

**Comment by ThomasFont3721** [comment]
ahhh d'accord non en effet je l'avais creer a partir de mongo merci
