### ISSUE TITLE
Create not working

### ISSUE THREAD

**Issue by ThomasFont3721** [dixplo/Projet-Board#2]
https://github.com/dixplo/Projet-Board/blob/be6c7d4ae4f42893c86b3639effaf799744cf5c8/app/routes/developers/add.js#L19

@jcheron 
Je viiens d'essqyer d'en sauvegarder 1 ais je n'y arrive pas non plus

**Comment by jcheron** [comment]
Il faut faire un **save**!
```javascript
        save(model) {
            let dev=this.get('store').createRecord('developer', model);
            dev.save();
        }
```
Et pourquoi utiliser **RSVP** alors que rien n'est chargé?

**Comment by ThomasFont3721** [comment]
Désolé c'est une erreur bete 😅
je voulais voir si sa fonctionner
