### ISSUE TITLE
Erreur de routes

### ISSUE THREAD

**Issue by ThomasFont3721** [dixplo/Projet-Board#3]
https://github.com/dixplo/Projet-Board/blob/837b7fdd994e1d942511deba3ec4419074cf67d3/app/router.js#L11-L12

@jcheron 
Es qu'il est possible d'utiliser la meme page pour deux route differente ?

**Comment by jcheron** [comment]
Non, pas de cette façon
Dîtes moi plutôt pourquoi vous voulez faire ça ?

**Comment by ThomasFont3721** [comment]
je voudrais utiliser le template du add pour ajouter un dev et pour l'editer

**Comment by jcheron** [comment]
Dans la route, vous pouvez redéfinir le templateName:
```javascript
export default Route.extend({
    templateName: 'add'
});
```

**Comment by ThomasFont3721** [comment]
merci monsieur
