### ISSUE TITLE
edit project

### ISSUE THREAD

**Issue by theomarie** [dixplo/Projet-Board#32]

**Comment by theomarie** [comment]
@jcheron 
Bonjour Mr ,
j'aurais besoin d’explication ou de lien qui me permettront de comprendre

je ne comprend pas comment manipuler le fichier edit.js correctement 
comment manipuler les données pour ensuite les passer dans le dropdown ou autres éléments fomantic ?
 En plus quand j'utilise le debugger,  pour aller voir les données si je récupère bien les développeurs je retrouve bien la propriété  développer seulement le contenue reste toujours vide.

![image](https://user-images.githubusercontent.com/34074097/77847327-a25cc300-71bc-11ea-9661-1b4599a1ffaa.png)

**Comment by jcheron** [comment]
Bonjour Théo,
Je ne comprends pas à quoi sert tout ce code:
https://github.com/dixplo/Projet-Board/blob/033f458766487d8e769a8fded1d6dda324fae0b6/app/routes/projects/edit.js#L8-L37
Pour moi, il suffit de retourner RSVP

**Comment by theomarie** [comment]
le code pour était pour insérer un tableaux de données dans la dropdown pour avec un résultat similaire 



les développeurs déjà dans le projet en prêt sélectionné 
![image](https://user-images.githubusercontent.com/34074097/77850292-be1e9400-71d1-11ea-92bf-2a81cc6e7f50.png)
