### ISSUE TITLE
Probleme avec le calendar

### ISSUE THREAD

**Issue by ThomasFont3721** [dixplo/Projet-Board#5]
https://github.com/dixplo/Projet-Board/blob/00e145a1998031c6b73b53c21f7c60119d5d09da/app/routes/application.js#L41-L48
https://github.com/dixplo/Projet-Board/blob/00e145a1998031c6b73b53c21f7c60119d5d09da/app/templates/application.hbs#L58-L79
[https://fomantic-ui.com/modules/calendar.html#range](url)

![image](https://user-images.githubusercontent.com/48830209/77053680-00c0bf00-69cf-11ea-9ba4-87fa3ee022cc.png)

j'aimerais avoir le meme resultat que sur fomantic mais je me retrouve avec une erreur 

ping @jcheron

**Comment by jcheron** [comment]
Vous avez ajouté jQuery ?

**Comment by ThomasFont3721** [comment]
oui j'ai ajouter jQuery mais je trouve plus jolie les calendar de fomantic

**Comment by jcheron** [comment]
Essayez en mettant ça dans la route:
```javascript
actions:{
    didTransition() {
      Ember.run.next(this, 'initUI');
    }
},
initUI() {
    Ember.$('#rangestart').calendar({ type: 'date', endCalendar: jQuery('#rangeend') }); 
    Ember.$('#rangeend').calendar({ type: 'date', startCalendar: jQuery('#rangestart') }); 
  }
```

**Comment by ThomasFont3721** [comment]
toujours la meme erreur

**Comment by ThomasFont3721** [comment]
je vais garder les calendar de base merci monsieur
