### ISSUE TITLE
get all data in project

### ISSUE THREAD

**Issue by ThomasFont3721** [dixplo/Projet-Board#6]
https://github.com/dixplo/Projet-Board/blob/81e4cba72ea1913a4222650f070d01c2666ddf89/app/models/project.js#L10-L13

J'ai ajouter cela pour charger les données directement mais il me sors une nouvelle erreur :

![image](https://user-images.githubusercontent.com/48830209/77411309-86bc7b80-6dbc-11ea-81bb-91bf16a66e11.png)

alors que j'appele mon projet avec les includes :
https://github.com/dixplo/Projet-Board/blob/81e4cba72ea1913a4222650f070d01c2666ddf89/app/routes/projects/project.js#L7-L10

ping @jcheron

**Comment by jcheron** [comment]
Ca risque d'être un peu long, faut que je mette en place votre projet sur ma machine...

**Comment by ThomasFont3721** [comment]
d'accord je vous remercie car a force j'ai l'impression d'avoir tous essayer

**Comment by jcheron** [comment]
Comment on y va sur la route en question ?
![image](https://user-images.githubusercontent.com/2511052/77418565-58906900-6dc7-11ea-92bc-f33124e434e2.png)

**Comment by ThomasFont3721** [comment]
http://127.0.0.1:4200/projects

**Comment by jcheron** [comment]
> http://127.0.0.1:4200/projects

J'y suis, et j'ai le screen 
![image](https://user-images.githubusercontent.com/2511052/77418910-da809200-6dc7-11ea-8079-6af9b142fdee.png)

**Comment by ThomasFont3721** [comment]
euh je comprend pas votre demande alors ?

**Comment by jcheron** [comment]
Ben votre pb semble être sur `projects/project/:project_id`
d'où ma question, comment à partir de `/projects` aller à `projects/project/:project_id`

**Comment by ThomasFont3721** [comment]
je viens de changer toutes les routes donc cela a totalement modifier 😅

**Comment by jcheron** [comment]
ok, donc pour l'instant, on peux pas y accéder ?
