### ISSUE TITLE
parcourir les liste des développeurs d'un projet 

### ISSUE THREAD

**Issue by theomarie** [dixplo/Projet-Board#7]
Je cherche a comprendre comment faire pour récupérer la liste des développeurs participants a un projet pour quand j'édite le projet il m'affiche les devs déjà a l'intérieur.

j'ai déjà récupérer la liste de tout les devs avec : 
 let developers = await this.store.findAll('developer') ;

pas possible de faire un 
 let developersInProject = await this.store.findAll('developer in project') ;

**Comment by ThomasFont3721** [comment]
apres ton findAll() fais :
`let developersInProject = await get(project, 'developers');`

**Comment by theomarie** [comment]
OK thomas 😂
